<a href="https://colab.research.google.com/github/victoriairungu99-creator/CDAV-course/blob/main/Copy_of_Day_9_week_2_Thursday_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spotify songs analytics dataset

In [ ]:
!pip install pandas #to install it on another platform other than colab

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
pd.__version__  #checks what version of panda you are using(is it one of the most recents or a bit dated back)

'2.2.2'

In [ ]:
counties=pd.Series([4397073,1208333,2162202,1157873])
print(counties)

0    4397073
1    1208333
2    2162202
3    1157873
dtype: int64

In [ ]:
df=pd.read_csv("/content/Popular_Spotify_Songs.csv", encoding='latin1')
df.head(10)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,...,141,C#,Major,92,66,58,19,0,8,24
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,...,148,F,Minor,67,83,76,48,0,8,3
7,Columbia,Quevedo,1,2023,7,7,714,43,58149378,25,...,100,F,Major,67,26,71,37,0,11,4
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,...,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,...,170,D,Minor,81,56,48,21,0,8,33

In [ ]:
df.tail(14)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
939,Spin Bout U,"Drake, 21 Savage",2,2022,11,4,1652,2,198365537,26,...,130,G,Major,77,20,70,1,0,16,5
940,Sweet Nothing,Taylor Swift,1,2022,10,21,1747,0,186104310,9,...,177,NaN,Major,34,39,16,97,0,12,5
941,"Would've, Could've, Should've",Taylor Swift,1,2022,10,21,1715,0,177503916,4,...,158,G,Major,48,55,84,43,0,15,12
942,Con La Brisa,"Ludwig Goransson, Foudeqush",2,2022,11,4,486,0,71095708,8,...,114,D,Minor,62,25,44,51,33,14,3
943,Privileged Rappers,"Drake, 21 Savage",2,2022,11,4,1007,0,112436403,6,...,144,F,Major,93,62,61,0,0,12,20
944,The Astronaut,Jin,1,2022,10,28,481,9,203436468,10,...,125,F,Major,54,22,76,0,0,14,3
945,BackOutsideBoyz,Drake,1,2022,11,4,1045,0,93367537,8,...,142,F,Minor,85,40,43,4,0,39,32
946,Broke Boys,"Drake, 21 Savage",2,2022,11,4,1060,0,106249219,3,...,120,D,Major,64,11,53,1,0,25,27
947,The Great War,Taylor Swift,1,2022,10,21,1274,0,181382590,1,...,96,F,Major,57,55,74,22,0,8,4
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [ ]:
df.shape # Gives you no. of rows and columns

(953, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [ ]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [ ]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=953, step=1)

In [ ]:
df.size

22872

In [ ]:
df.dtypes

track_name              object
artist(s)_name          object
artist_count             int64
released_year            int64
released_month           int64
released_day             int64
in_spotify_playlists     int64
in_spotify_charts        int64
streams                 object
in_apple_playlists       int64
in_apple_charts          int64
in_deezer_playlists     object
in_deezer_charts         int64
in_shazam_charts        object
bpm                      int64
key                     object
mode                    object
danceability_%           int64
valence_%                int64
energy_%                 int64
acousticness_%           int64
instrumentalness_%       int64
liveness_%               int64
speechiness_%            int64
dtype: object

In [ ]:
df["released_year"]#gives you one column

0      2023
1      2023
2      2023
3      2019
4      2023
       ...
948    2022
949    2022
950    2022
951    2022
952    2022
Name: released_year, Length: 953, dtype: int64

In [ ]:
df[["released_year","released_month"]]#gives you two columns

     released_year  released_month
0             2023               7
1             2023               3
2             2023               6
3             2019               8
4             2023               5
..             ...             ...
948           2022              11
949           2022              10
950           2022              11
951           2022              10
952           2022              11

[953 rows x 2 columns]

In [ ]:
df[["released_year","released_month","released_day"]]

     released_year  released_month  released_day
0             2023               7            14
1             2023               3            23
2             2023               6            30
3             2019               8            23
4             2023               5            18
..             ...             ...           ...
948           2022              11             3
949           2022              10            21
950           2022              11             3
951           2022              10            20
952           2022              11             4

[953 rows x 3 columns]

In [ ]:
df.loc[24,"artist_count"] #checks the value or object in the row indicated and the respective column

np.int64(3)

In [ ]:
df.iloc[24,3]

np.int64(2023)

In [ ]:
df[ df["in_spotify_playlists"] > 2000]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,...,141,C#,Major,92,66,58,19,0,8,24
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,...,148,F,Minor,67,83,76,48,0,8,3
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,...,170,D,Minor,81,56,48,21,0,8,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,Sparks,Coldplay,1,2000,7,10,10826,4,624101957,24,...,103,C#,Major,37,17,27,75,5,10,3
914,Selfish,PnB Rock,1,2016,6,23,2468,0,380319238,15,...,102,C#,Minor,64,4,60,11,0,19,4
922,Miss You,Southstar,1,1982,5,16,2020,0,154356956,77,...,145,A,Major,66,24,58,17,0,19,5
923,we fell in love in october,girl in red,1,2018,11,21,6858,0,723043854,31,...,130,G,Major,57,24,37,11,18,16,3
924,2 Be Loved (Am I Ready),Lizzo,1,2022,7,14,3682,6,247689123,41,...,156,G,Major,72,92,77,9,0,8,11

In [ ]:
is_major=df["mode"]=="Major"
is_large=df["bpm"]>150

df[is_major&is_large]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
28,Last Night,Morgan Wallen,1,2023,1,31,2420,19,429829812,52,...,204,F#,Major,52,52,68,46,0,15,4
31,TULUM,"Peso Pluma, Grupo Frontera",2,2023,6,28,266,34,52294266,20,...,168,F#,Major,56,63,87,39,0,11,5
48,Starboy,"The Weeknd, Daft Punk",2,2016,9,21,29536,79,2565529693,281,...,186,G,Major,68,49,59,16,0,13,28
55,Blinding Lights,The Weeknd,1,2019,11,29,43899,69,3703895074,672,...,171,C#,Major,50,38,80,0,0,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,2 Be Loved (Am I Ready),Lizzo,1,2022,7,14,3682,6,247689123,41,...,156,G,Major,72,92,77,9,0,8,11
935,On BS,"Drake, 21 Savage",2,2022,11,4,1338,0,170413877,9,...,158,A,Major,84,33,36,2,0,39,59
940,Sweet Nothing,Taylor Swift,1,2022,10,21,1747,0,186104310,9,...,177,NaN,Major,34,39,16,97,0,12,5
941,"Would've, Could've, Should've",Taylor Swift,1,2022,10,21,1715,0,177503916,4,...,158,G,Major,48,55,84,43,0,15,12
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6

In [ ]:
len("released_month")
df["released_month"].shape

(953,)

In [ ]:
df["track_name"].shape

(953,)

In [ ]:
df[(df["mode"]=="Minor")|(df["bpm"]==130)]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,...,148,F,Minor,67,83,76,48,0,8,3
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,...,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,...,170,D,Minor,81,56,48,21,0,8,33
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,...,83,F#,Minor,57,56,72,23,0,27,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,Vigilante Shit,Taylor Swift,1,2022,10,21,1948,0,253650850,12,...,80,E,Minor,80,16,28,17,0,12,39
939,Spin Bout U,"Drake, 21 Savage",2,2022,11,4,1652,2,198365537,26,...,130,G,Major,77,20,70,1,0,16,5
942,Con La Brisa,"Ludwig Goransson, Foudeqush",2,2022,11,4,486,0,71095708,8,...,114,D,Minor,62,25,44,51,33,14,3
945,BackOutsideBoyz,Drake,1,2022,11,4,1045,0,93367537,8,...,142,F,Minor,85,40,43,4,0,39,32
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [ ]:
df[df["track_name"].isin(["mode"])] #for printing out a specific dataset of a given condition for example this one is for track names that are in the mode minor
df[df["mode"]=="Minor"]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,...,148,F,Minor,67,83,76,48,0,8,3
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,...,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,...,170,D,Minor,81,56,48,21,0,8,33
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,...,83,F#,Minor,57,56,72,23,0,27,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,Pussy & Millions (feat. Travis Scott),"Drake, Travis Scott, 21 Savage",3,2022,11,4,1930,0,191333656,24,...,122,E,Minor,75,45,63,6,0,35,12
933,Vigilante Shit,Taylor Swift,1,2022,10,21,1948,0,253650850,12,...,80,E,Minor,80,16,28,17,0,12,39
942,Con La Brisa,"Ludwig Goransson, Foudeqush",2,2022,11,4,486,0,71095708,8,...,114,D,Minor,62,25,44,51,33,14,3
945,BackOutsideBoyz,Drake,1,2022,11,4,1045,0,93367537,8,...,142,F,Minor,85,40,43,4,0,39,32
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [ ]:
df.isna()#checks what cells are missing a value(true for whtre a value is missing and false for where a value is available)(isna means is null)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
949,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
950,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
951,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
952,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()#count per column

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [ ]:
df.isna().sum().sum()#total acros  the whole table

np.int64(145)

In [ ]:
df.isna().mean()*100#percentage missing per column

track_name              0.00000
artist(s)_name          0.00000
artist_count            0.00000
released_year           0.00000
released_month          0.00000
released_day            0.00000
in_spotify_playlists    0.00000
in_spotify_charts       0.00000
streams                 0.00000
in_apple_playlists      0.00000
in_apple_charts         0.00000
in_deezer_playlists     0.00000
in_deezer_charts        0.00000
in_shazam_charts        5.24659
bpm                     0.00000
key                     9.96852
mode                    0.00000
danceability_%          0.00000
valence_%               0.00000
energy_%                0.00000
acousticness_%          0.00000
instrumentalness_%      0.00000
liveness_%              0.00000
speechiness_%           0.00000
dtype: float64

In [ ]:
df["in_shazam_charts"].fillna(0,inplace=True)

/tmp/ipykernel_15868/1353844102.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["in_shazam_charts"].fillna(0,inplace=True)

In [ ]:
df['in_shazam_charts'] = pd.to_numeric(df['in_shazam_charts'], errors='coerce')
df['in_shazam_charts'].fillna(df['in_shazam_charts'].mean(), inplace=True)

/tmp/ipykernel_15868/1407603421.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['in_shazam_charts'].fillna(df['in_shazam_charts'].mean(), inplace=True)

In [ ]:
df.isna().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts         0
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [track_name, artist(s)_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, in_apple_playlists, in_apple_charts, in_deezer_playlists, in_deezer_charts, in_shazam_charts, bpm, key, mode, danceability_%, valence_%, energy_%, acousticness_%, instrumentalness_%, liveness_%, speechiness_%]
Index: []

[0 rows x 24 columns]

In [ ]:
#filtering out data to remain w a specific dataset
import pandas as pd
df=pd.read_csv("/content/Popular_Spotify_Songs.csv", encoding='latin1')

In [ ]:
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [ ]:
released=[df["released_year"]==2023]

In [ ]:
# The 'released' variable is currently a list containing a boolean Series.
# We need to use this boolean Series to filter the original 'df' DataFrame.
filtered_df = df[released[0]]
filtered_df.to_excel("clean.xlsx", index=False)

In [ ]:
df=pd.read_excel("/content/clean.xlsx")

In [ ]:
df.head(22)

,Unnamed: 0,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,...,125,B,Major,80,89,83,31,0,8,4
1,1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,...,92,C#,Major,71,61,74,7,0,10,4
2,2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,...,138,F,Major,51,32,53,17,0,31,6
3,4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,...,144,A,Minor,65,23,80,14,63,11,6
4,5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,...,141,C#,Major,92,66,58,19,0,8,24
5,6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,...,148,F,Minor,67,83,76,48,0,8,3
6,7,Columbia,Quevedo,1,2023,7,7,714,43,58149378,...,100,F,Major,67,26,71,37,0,11,4
7,8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,...,130,C#,Minor,85,22,62,12,0,28,9
8,9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,...,170,D,Minor,81,56,48,21,0,8,33
9,10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,...,83,F#,Minor,57,56,72,23,0,27,5
10,11,Super Shy,NewJeans,1,2023,7,7,422,55,58255150,...,150,F,Minor,78,52,82,18,0,15,7
11,12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,...,118,NaN,Major,71,65,68,6,0,3,7
12,13,Daylight,David Kushner,1,2023,4,14,3528,98,387570742,...,130,D,Minor,51,32,43,83,0,9,3
13,16,Cupid - Twin Ver.,Fifty Fifty,1,2023,2,24,2942,77,496795686,...,120,B,Minor,78,76,59,43,0,34,3
14,17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,1,2023,7,13,873,104,30546883,...,78,NaN,Major,44,14,9,96,0,10,3
15,18,Classy 101,"Feid, Young Miko",2,2023,3,31,2610,40,335222234,...,100,B,Major,86,67,66,14,0,12,16
16,19,Like Crazy,Jimin,1,2023,3,24,596,68,363369738,...,120,G,Major,63,36,73,0,0,36,4
17,20,LADY GAGA,"Gabito Ballesteros, Junior H, Peso Pluma",3,2023,6,22,332,26,86444842,...,140,F,Minor,65,87,74,22,0,42,4
18,21,I Can See You (Taylorï¿½ï¿½ï¿½s Version) (From...,Taylor Swift,1,2023,7,7,516,38,52135248,...,123,F#,Major,69,82,76,6,0,6,3
19,23,"Peso Pluma: Bzrp Music Sessions, Vol. 55","Bizarrap, Peso Pluma",2,2023,5,31,1313,40,200647221,...,133,F,Minor,85,81,67,26,0,12,5
20,24,Popular (with Playboi Carti & Madonna) - The I...,"The Weeknd, Madonna, Playboi Carti",3,2023,6,2,1945,87,115364561,...,99,C#,Major,85,83,68,7,0,36,20
21,25,SABOR FRESA,Fuerza Regida,1,2023,6,22,250,26,78300654,...,130,G,Minor,79,96,86,9,0,9,9

In [ ]:
import pandas as pd
df=pd.read_csv("/content/kenya_transactions_messy.csv")

In [ ]:
df.head(33)

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,06/05/2026,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P
5,TXN00554,"Atieno, Ann",Eldoret,-207,30/06/2026,24/07/2026,888.0,P
6,TXN00673,"Ochieng, Mary",Unknown,829,09/06/2026,06/05/2026,694.2,P
7,TXN00750,"Wafula, Mercy",Nakuru,-260,28/01/2026,05/02/2026,1334.8,?
8,TXN00139,"Otieno, Ann",Mombasa,402,13/01/2026,15/01/2026,921.2,P
9,TXN00477,"Njoroge, George",Eldoret,560 KES,17/01/2026,20/01/2026,1106.8,P
10,TXN00478,"Kimani, Felix",Meru,947,01/02/2026,03/03/2026,1667.4,?
11,TXN00617,"Wafula, Kevin",Nairobi,681,05/01/2026,21/01/2026,1174.3,P
12,TXN00242,"Atieno, Samuel",Nairobi,7017,01/04/2026,02/04/2026,1185.3,Unknown
13,TXN00093,"Mwangi, Rose",Mombasa,3441,30/06/2026,19/07/2026,313.0,U
14,TXN00306,"Mwangi, Purity",Nairobi,9111,06/01/2026,18/01/2026,436.4,P
15,TXN00054,"Kariuki, Nancy",Nakuru,0,09/03/2026,02/04/2026,874.0,P
16,TXN00023,"Cheruiyot, David",nairobi,466,07/03/2026,01/04/2026,827.3,P
17,TXN00184,"Omondi, Jane",Machakos,-318,06/06/2026,10/06/2026,995.5,U
18,TXN00216,"Njoroge, George",Nairobi,609,15/04/2026,03/05/2026,1258.8,P
19,TXN00147,"Auma, Rose",Kakamega,"2,456",07/05/2026,22/05/2026,1272.1,?
20,TXN00855,"Muthoni, Samuel",Kitale,496,04/01/2026,30/01/2026,1747.7,P
21,TXN00769,"Ochieng, Sarah",Kiambu,523,10/02/2026,09/03/2026,437.9,?
22,TXN00747,"Wambui, Michael",Nairobi,171,09/05/2026,14/05/2026,1620.8,U
23,TXN00561,"Kamau, Ann",Meru,1734,20/06/2026,17/07/2026,575.5,P
24,TXN00550,"Achieng, Samuel",Nairobi,4086,13/04/2026,06/05/2026,858.6,?
25,TXN00374,"Nyongesa, Michael",Kisumu,1824,30/06/2026,09/07/2026,1129.0,P
26,TXN00008,"Rotich, Anthony",Kajiado,9808,24/06/2026,24/07/2026,1309.9,U
27,TXN00703,"Chebet, Alice",Machakos,470,30/05/2026,06/05/2026,318.8,P
28,TXN00173,"Wambui, Faith",Meru,"3,401",26/06/2026,12/07/2026,1116.4,U
29,TXN00751,"Waweru, Peter",Nyeri,863,23/06/2026,21/07/2026,1670.2,?
30,TXN00886,"Ochieng, Collins",Eldoret,252,25/04/2026,27/04/2026,951.2,P
31,TXN00180,"Kirui, Winnie",Mombasa,692,25/02/2026,25/03/2026,812.5,?
32,TXN00495,"Achieng, Beatrice",NYERI,695,26/05/2026,18/06/2026,873.2,U

In [ ]:
df.shape#how many rows and columns are there

(1000, 8)

In [ ]:
df.describe()

       Rainfall mm
count   963.000000
mean    956.926376
std     439.099355
min     180.800000
25%     585.650000
50%     952.400000
75%    1316.050000
max    1747.800000

In [ ]:
#cleaning the data
df.isna().sum()#which columns have null(missing) values

Txn ID             0
Full Name          0
County             7
 Amount Paid      40
Txn Date           0
Paid Date        151
Rainfall mm       37
Status           121
dtype: int64

In [ ]:

df["Rainfall mm"].fillna(df["Rainfall mm"].mean())

0       222.9
1       902.6
2      1122.0
3       509.3
4      1193.9
        ...
995     896.8
996     639.9
997    1208.0
998    1636.0
999       0.0
Name: Rainfall mm, Length: 1000, dtype: float64

In [ ]:
df["Amount Paid"]=df["Amount Paid"].fillna(0)

In [ ]:
df["Amount Paid"].fillna("Unknown")

0         76
1          -
2       6920
3       4342
4        452
       ...
995    11105
996    17377
997      153
998     4862
999     1021
Name: Amount Paid, Length: 1000, dtype: object

In [ ]:
df.isna().sum()

Txn ID         0
Full Name      0
County         0
Amount Paid    0
Txn Date       0
Paid Date      0
Rainfall mm    0
Status         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(40)

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
df[df.duplicated()]

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
161,TXN00750,"Wafula, Mercy",Nakuru,-260,28/01/2026,05/02/2026,1334.8,?
235,TXN00562,"Waweru, Samuel",Kiambu,754,23/06/2026,NaN,0.0,U
263,TXN00855,"Muthoni, Samuel",Kitale,496,04/01/2026,30/01/2026,1747.7,P
286,TXN00001,"Kiptoo, Samuel",Kiambu,608,24/01/2026,NaN,973.4,P
314,TXN00840,"Korir, Alice",Kericho,3805,22/05/2026,26/05/2026,412.8,P
320,TXN00734,"Omondi, Grace",nairobi,4507 KES,05/02/2026,07/03/2026,586.7,P
423,TXN00148,"Muthoni, Paul",nairobi,3042,18/02/2026,21/02/2026,1314.2,NaN
445,TXN00772,"Ochieng, James",BUNGOMA,"3,193 KES",18/05/2026,05/06/2026,781.2,U
473,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
497,TXN00418,"Ochieng, Dennis",Kakamega,-,28/05/2026,12/06/2026,1482.4,U
500,TXN00770,"Mwangi, Felix",Meru,2437,11/01/2026,21/01/2026,1161.2,U
506,TXN00517,"Kimani, Ann",Mombasa,96,13/06/2026,NaN,1276.5,NaN
539,TXN00917,"Auma, Grace",Nairobi,131 KES,24/03/2026,30/03/2026,1283.5,P
577,TXN00591,"Atieno, Kevin",Nakuru,793,07/02/2026,19/02/2026,850.6,NaN
593,TXN00705,"Wanjiku, Lucy",Kilifi,391 KES,27/04/2026,28/04/2026,1097.8,U
606,TXN00232,"Muthoni, Lucy",Meru,"4,660",09/02/2026,25/02/2026,803.5,P
616,TXN00111,"Maina, Stephen",NAIROBI,-655,15/01/2026,24/01/2026,1297.5,?
618,TXN00160,"Achieng, Mary",Kisumu,3557,18/05/2026,30/05/2026,1318.0,U
651,TXN00813,"Achieng, Rose",Kitale,300,15/02/2026,NaN,0.0,?
717,TXN00193,"Owino, Purity",Machakos,7079,16/02/2026,11/03/2026,1391.1,P
751,TXN00334,"Rotich, David",Mombasa,798,06/04/2026,16/04/2026,1462.9,U
761,TXN00673,"Ochieng, Mary",NaN,829,09/06/2026,NaN,694.2,P
766,TXN00383,"Njoroge, Ruth",Eldoret,2839,13/04/2026,30/04/2026,232.5,P
782,TXN00915,"Omondi, Alice",Meru,"1,766",03/05/2026,09/05/2026,1634.7,P
783,TXN00830,"Kimani, Michael",Kisumu,2757,11/03/2026,14/03/2026,1193.9,P
788,TXN00508,"Wanjiku, George",Nairobi,3667,12/05/2026,07/06/2026,1376.3,U
797,TXN00109,"Barasa, Peter",Nyeri,429,12/03/2026,28/03/2026,673.6,P
801,TXN00711,"Auma, Eric",Nairobi,-771,12/02/2026,04/03/2026,712.7,?
810,TXN00465,"Waweru, Rose",Nairobi,"18,506",16/04/2026,18/04/2026,1125.3,NaN
859,TXN00857,"Auma, Dennis",NAIROBI,205,06/06/2026,NaN,809.4,U
862,TXN00403,"Ochieng, Ruth",Kiambu,"4,193",08/05/2026,25/05/2026,1493.2,NaN
899,TXN00820,"Njeri, Brian",Mombasa,545,13/03/2026,NaN,504.1,P
901,TXN00768,"Korir, George",Meru,16795,05/04/2026,21/04/2026,1576.6,U
928,TXN00536,"Auma, Beatrice",Nairobi,"19,920",24/03/2026,28/03/2026,1416.2,P
934,TXN00817,"Onyango, Stephen",Kakamega,"1,192",10/03/2026,10/03/2026,762.2,P
939,TXN00656,"Chebet, Ruth",Kitale,266,02/04/2026,22/04/2026,402.5,P
967,TXN00405,"Rotich, Winnie",Kiambu,141,25/04/2026,10/05/2026,503.7,?
973,TXN00938,"Rotich, Brian",Machakos,9352,29/05/2026,03/06/2026,1364.0,P
986,TXN00360,"Ochieng, Ann",KERICHO,1618,17/03/2026,11/04/2026,630.9,U
997,TXN00225,"Barasa, David",Kisumu,153,05/04/2026,18/04/2026,1208.0,U

In [ ]:
df.drop_duplicates()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,NaN,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P
...,...,...,...,...,...,...,...,...
994,TXN00774,"Mutua, Ruth",Nairobi,562,05/01/2026,17/01/2026,737.3,NaN
995,TXN00248,"Rotich, Stephen",Nairobi,11105,06/06/2026,18/06/2026,896.8,NaN
996,TXN00314,"Auma, Samuel",Mombasa,17377,17/01/2026,NaN,639.9,P
998,TXN00712,"Cheruiyot, Jane",Kericho,4862,09/02/2026,14/02/2026,1636.0,NaN
999,TXN00074,"Nyongesa, Joyce",Nairobi,1021,05/02/2026,15/02/2026,0.0,P

In [ ]:
df["County"]=df["County"].fillna("Unknown")

In [ ]:
df["County"].fillna("Unknown")

0        NAIROBI
1         Kisumu
2         Kiambu
3        Kajiado
4         Kisumu
         ...
995      Nairobi
996      Mombasa
997       Kisumu
998     Kericho
999     Nairobi
Name: County, Length: 1000, dtype: object

In [ ]:
df["Status"]=df["Status"].fillna("Unknown")

In [ ]:
df["Status"].fillna("Unknown")

0            ?
1            P
2            P
3            P
4            P
        ...
995    Unknown
996          P
997          U
998    Unknown
999          P
Name: Status, Length: 1000, dtype: object

In [ ]:
df["Paid Date"]=df["Paid Date"].fillna(df["Paid Date"].mode()[0])

In [ ]:
import pandas as pd
df=pd.read_csv("/content/kenya_transactions_messy.csv")
print("Before: ",df.columns.tolist()) #shows you how the columns look to see if there is any error like space before or after punctuation marks

Before:  ['Txn ID', 'Full Name', 'County ', ' Amount Paid ', 'Txn Date', 'Paid Date', 'Rainfall mm', 'Status']

In [ ]:
#makes the necessary changes
df.columns=(
    df.columns.str.strip()
    .str.lower()
    .str.replace(' ','_')
)

In [ ]:
#Verify
print("After: ",df.columns.tolist())

After:  ['txn_id', 'full_name', 'county', 'amount_paid', 'txn_date', 'paid_date', 'rainfall_mm', 'status']

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df = df.rename(columns={'amount_paid': 'amount'})
df.columns          # clean names, after

Index(['txn_id', 'full_name', 'county', 'amount', 'txn_date', 'paid_date',
       'rainfall_mm', 'status'],
      dtype='object')

In [ ]:
clean = (df['amount'].astype(str)
                     .str.replace(',', '', regex=False)
                     .str.replace(' KES', '', regex=False)
                     .str.strip())
df['amount'] = pd.to_numeric(clean, errors='coerce')
df['amount'].dtype        # now a real number

dtype('float64')

In [ ]:
#errors='coerce' - Turns anything that is not numeric to NaN or a misiing value

In [ ]:
df["county"]=df["county"].str.strip().str.title()

In [ ]:
df.groupby("county")["amount"].sum().sort_values(ascending= True)

county
Nairobi​     16612.0
Kilifi       73818.0
Kakamega     87412.0
Kitale       90747.0
Bungoma      92265.0
Nyeri        99230.0
Kericho     120444.0
Kajiado     134732.0
Meru        136987.0
Machakos    153518.0
Kiambu      158547.0
Eldoret     181858.0
Kisumu      198972.0
Nakuru      232432.0
Mombasa     359038.0
Nairobi     632492.0
Name: amount, dtype: float64

In [ ]:
df.groupby("county")["amount"].max()

county
Bungoma     19543.0
Eldoret     19434.0
Kajiado     17990.0
Kakamega    12363.0
Kericho     18183.0
Kiambu      19676.0
Kilifi      16898.0
Kisumu      17072.0
Kitale      19753.0
Machakos    19824.0
Meru        16795.0
Mombasa     18830.0
Nairobi     19936.0
Nairobi​     2946.0
Nakuru      19676.0
Nyeri       17650.0
Name: amount, dtype: float64

In [ ]:
df.groupby("county")["amount"].agg(["count","sum","mean"])#.agg displays a lot of calculations at once

          count       sum         mean
county
Bungoma      25   92265.0  3690.600000
Eldoret      67  181858.0  2714.298507
Kajiado      38  134732.0  3545.578947
Kakamega     37   87412.0  2362.486486
Kericho      29  120444.0  4153.241379
Kiambu       61  158547.0  2599.131148
Kilifi       33   73818.0  2236.909091
Kisumu       87  198972.0  2287.034483
Kitale       26   90747.0  3490.269231
Machakos     47  153518.0  3266.340426
Meru         42  136987.0  3261.595238
Mombasa     121  359038.0  2967.256198
Nairobi     191  632492.0  3311.476440
Nairobi​     17   16612.0   977.176471
Nakuru       71  232432.0  3273.690141
Nyeri        41   99230.0  2420.243902

In [ ]:
df["amount"].nlargest(3)

728    19936.0
114    19920.0
928    19920.0
Name: amount, dtype: float64

In [ ]:
df.groupby(["county","status"])["amount"].sum()

county    status
Bungoma   ?           5814.0
          P          71023.0
          U          10933.0
Eldoret   ?          41646.0
          P          89324.0
          U          33070.0
Kajiado   ?          25391.0
          P          59442.0
          U          45758.0
Kakamega  ?           9671.0
          P          34820.0
          U          38837.0
Kericho   ?          21185.0
          P          50844.0
          U          27914.0
Kiambu    ?          10082.0
          P          61141.0
          U          73795.0
Kilifi    ?          20820.0
          P          21658.0
          U          26913.0
Kisumu    ?          30338.0
          P          74798.0
          U          60639.0
Kitale    ?          47292.0
          P          30131.0
          U          12830.0
Machakos  ?           4042.0
          P          62583.0
          U          64797.0
Meru      ?          21932.0
          P          49529.0
          U          63535.0
Mombasa   ?          79985.0
          P         153949.0
          U          61384.0
Nairobi   ?          66811.0
          P         328318.0
          U         145446.0
Nairobi​  ?           2126.0
          P           7364.0
          U           3560.0
Nakuru    ?           3072.0
          P         151279.0
          U          39310.0
Nyeri     ?          15194.0
          P          26993.0
          U          50016.0
Name: amount, dtype: float64